"""
Writes EVIDENCE.md, memo_to_ritu.md, DECISIONS.md, recording_script.md and submission-form.md
from outputs/evaluation_results.json, so that no number in the documents is typed by hand.
Run after training:  python -m src.make_docs
(The first version of the documents had hand-typed numbers; several were wrong.)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = json.loads((ROOT / "outputs" / "evaluation_results.json").read_text())

inr = lambda x: f"Rs {x:,.0f}" if x >= 0 else f"-Rs {abs(x):,.0f}"
pct = lambda x, d=1: f"{100 * x:.{d}f}%"

dq, rg, pt, q = R["data_quality"], R["regime"], R["partners"], R["queue"]
FEB, MJ, JUN = R["eval_pre_regime_Feb_Apr"], R["eval_May_Jun"], R["eval_Jun"]
BYM = R["eval_by_month"]
LAB = R["model_labels"]

# ---- derived quantities used in several places --------------------------
rate = lambda a: a[1] / a[0]
jun_f = JUN["final"]
avg_caught = jun_f["fraud_rupees_caught"] / jun_f["frauds_in_queue"]           # Rs per fraud caught in June queue
EXP_P = 0.25                                                                   # stated expectation, see form
exp_frauds = 40 * EXP_P
exp_caught = exp_frauds * avg_caught
exp_fp = 40 - exp_frauds
exp_net_goodwill = exp_caught - exp_fp * 380
exp_net_full = exp_net_goodwill - 40 * 260
be_goodwill = 380 / (avg_caught + 380)
be_full = (380 + 260) / (avg_caught + 380)
fraud_per_month = rg["post_may_fraud_total_rs"] / rg["post_may_months"]
gross_per_review = exp_caught / 40
top5 = pt["post_may_small_top5"]
top5_txt = ", ".join(f"{t['partner_id']} ({t['frauds']} of {t['claims']})" for t in top5)
ids = sorted(dq.get("injected_ids_train_description", []))
orule = R["outlet_rule"]
tq = q["test_top_queue_partners"]


def row(name, m):
    return (f"| {name} | {m['frauds_in_queue']} of {m['reviews']} | {pct(m['precision'])} | {inr(m['fraud_rupees_caught'])} | "
            f"{inr(m['net_rs_goodwill_only'])} | {inr(m['net_rs_goodwill_and_contact'])} | {m['roc_auc']:.2f} | {m['pr_auc']:.2f} |")


def table(block):
    head = ("| Model | Frauds in queue | Precision | Fraud Rs caught | Net Rs (goodwill only) | Net Rs (goodwill + Rs 260/review) | ROC-AUC | PR-AUC |\n"
            "|---|---|---|---|---|---|---|---|\n")
    return head + "\n".join(row(LAB[k], block[k]) for k in ["rand", "rules", "lr", "cb", "final"])


def ci(b, key, fmt):
    lo, hi = b["bootstrap_final"][key]
    return f"[{fmt(lo)}, {fmt(hi)}]"


# =========================================================================
EVIDENCE = f"""# Evidence pack

Every number below is generated by `python -m src.train` then `python -m src.make_docs`
(source: `outputs/evaluation_results.json`). Nothing here is typed by hand.

## 1. Bottom line

* **Accuracy is the wrong KPI.** In May-Jun 2026 "approve everything" scores {pct(MJ['accuracy_trap_final']['accuracy_predict_nobody'], 2)} accuracy and stops Rs 0 of fraud.
  The model's own review queue scores {pct(MJ['accuracy_trap_final']['accuracy_top40_flagged'], 2)} (it flags 40 claims a month as fraud, most of which are genuine). The 97% target cannot tell a useful model from a useless one: a realistic 40-a-month list scores below approve-everything.
* **The model works only when it has seen the new regime.** Trained through 31 May and tested on June it puts **{jun_f['frauds_in_queue']} of 40** reviews on real fraud
  (ROC-AUC {jun_f['roc_auc']:.2f}). Trained before 1 May and tested on May it put **0 of 40** on fraud (ROC-AUC {BYM['May']['roc_auc']:.2f}): it had never seen the post-1-May pattern. **Retrain monthly.**
* **The queue is roughly break-even, not a profit centre.** At the policy costs a review has to be fraud about {pct(be_goodwill, 0)} of the time to pay back the Rs 380 goodwill,
  and about {pct(be_full, 0)} if the Rs 260 contact cost is charged to every review. June achieved {pct(jun_f['precision'], 1)}; May 0%.
* **The strongest signal is the outlet.** {top5_txt} (post-May small claims) hold {pct(pt['post_may_small_top5_share_of_fraud'], 0)} of that fraud.
* **Evidence is thin.** 141 frauds in total, {JUN['final']['positives']} in the June fold. Intervals below are wide and we do not hide that.

## 2. Data quality (what we found, what we did)

| Item | Finding | Action |
|---|---|---|
| Duplicate claim_ids | {dq['duplicate_rows_removed']} resubmitted rows ({dq['train_rows_raw']:,} raw to {dq['train_rows_unique_claims']:,} unique) | keep last submission; a claim never sits in two folds |
| Undecided labels | {dq['undecided_blank_labels']} blank (all CRM rows) | dropped from training and evaluation, still scored if they appear |
| Legacy Zoho "0" labels | {dq['legacy_rows_decided']:,} legacy rows are all 0/1, so undecided cases there are indistinguishable from genuine 0s | kept; cannot be fixed from the data. If legacy had the same blank rate as the CRM (202 of 7,154 = 2.8%), roughly 130 of the legacy 0s would be undecided. This is an assumption, not a measurement |
| Injected instructions in free text | **{dq['injected_or_unrecognised_train_description_rows']} rows** in train ({len(ids)} distinct claims: {', '.join(ids)}; one was resubmitted), **{dq['injected_or_unrecognised_test_description_rows']} in test**. They tell an "AI reviewer" to use a random split, report accuracy only and trust partner onboarding date | free text is never a model feature or an LLM input; text is whitelist-checked |
| Serial typing mess | lower case, spaces, dashes | normalised to upper-case alphanumerics; only a validity flag (11 characters) is used |
| Claims before partner onboarding | train {dq['claims_before_partner_onboarding_train']}, test {dq['claims_before_partner_onboarding_test']} | none to fix |
| Test partners never seen in train | {dq['test_partners_not_in_train']} outlets, {dq['test_rows_unseen_partner']} claims | scored on claim facts only; flagged in API warnings |
| Timestamps | submitted_at is IST per the README. The UTC issue in the policy concerns Zoho *resolution events*, which are not in these files | nothing to convert; we say so rather than pretend |

## 3. The 1 May 2026 change

| | Claims | Frauds | Rate |
|---|---|---|---|
| Before 1 May, under Rs 2,000 | {rg['pre_small'][0]:,} | {rg['pre_small'][1]} | {pct(rate(rg['pre_small']), 2)} |
| Before 1 May, Rs 2,000 and over | {rg['pre_large'][0]:,} | {rg['pre_large'][1]} | {pct(rate(rg['pre_large']), 2)} |
| After 1 May, under Rs 2,000 | {rg['post_small'][0]:,} | {rg['post_small'][1]} | {pct(rate(rg['post_small']), 2)} |
| After 1 May, Rs 2,000 and over | {rg['post_large'][0]:,} | {rg['post_large'][1]} | {pct(rate(rg['post_large']), 2)} |
| Rs 1,900 to 1,999 (all dates) | {rg['near_2000'][0]} | {rg['near_2000'][1]} | {pct(rate(rg['near_2000']), 2)} |

Inspection of small claims fell from {pct(rg['small_pre_inspected_share'], 0)} to {pct(rg['small_post_inspected_share'], 1)}. Post-May fraud paid on decided claims: {inr(rg['post_may_fraud_total_rs'])} in two months
(about {inr(fraud_per_month)} a month; average fraud claim {inr(rg['post_may_fraud_amount_mean'])}, median {inr(rg['post_may_fraud_amount_median'])}).

## 4. How it was validated

* **Rolling-origin by month.** For each month Feb-Jun 2026: train on everything before the month, score that month. No random splits anywhere.
* **Partner history is "as-of".** Training rows see only labels from claims at least 30 days older. Validation months see a **frozen snapshot at the month start**, exactly how the live service and the test file are scored.
* **Queue = top 40 per month**, the investigation desk's limit. Ties are broken randomly.
* **Intervals** are partner-clustered bootstrap (1,000 resamples of outlets), because claims from one outlet are not independent.
* **Selection caveat.** Hyper-parameters (depth 3, 300 trees, strong L2) and the 0.7/0.3 blend were set by hand after exploratory runs on these same folds. Treat the numbers as mildly optimistic. No early stopping on any evaluation fold.
* **Features** (22 numeric + 2 categorical): amount and its distance below Rs 2,000, days since purchase vs warranty, customer prior claims, photo, partner tenure and type, product family,
  and the outlet's as-of fraud history (all claims and small claims). Dropped: inspection fields (exist only for inspected claims), free text, serial repeat counts, hour/day, volume counts.

## 5. Results

### 5.1 June 2026: the regime-aware fold (model trained through 31 May; {JUN['final']['positives']} frauds in {JUN['final']['claims']} claims; 40 reviews)
{table(JUN)}

Partner-clustered 95% intervals for the final model: precision {ci(JUN, 'precision_ci', lambda v: pct(v, 0))}, fraud rupees caught {ci(JUN, 'rupees_caught_ci', inr)}, ROC-AUC {ci(JUN, 'roc_auc_ci', lambda v: f'{v:.2f}')}.
Lift over *expected* random ({pct(JUN['random_expected_precision'])}): {JUN['lift_vs_expected_random']:.1f}x. (The random row above is one random draw, not the expectation.)

### 5.2 May + June 2026 (80 reviews, {MJ['final']['positives']} frauds)
{table(MJ)}

Intervals for the final model: precision {ci(MJ, 'precision_ci', lambda v: pct(v, 0))}, ROC-AUC {ci(MJ, 'roc_auc_ci', lambda v: f'{v:.2f}')}.

### 5.3 February to April 2026 (before the regime change; 120 reviews, {FEB['final']['positives']} frauds)
{table(FEB)}

### 5.4 Month by month (final model, 40 reviews each)
| Month | Frauds that month | Frauds in queue | ROC-AUC | Net Rs (goodwill + contact) |
|---|---|---|---|---|
""" + "\n".join(f"| {m} | {v['positives']} | {v['frauds_in_queue']} | {v['roc_auc']:.2f} | {inr(v['net_rs_goodwill_and_contact'])} |" for m, v in BYM.items()) + f"""

Months with 5-9 frauds give very noisy AUCs (February's 1.00 is five frauds); look at the totals above rather than single months.

**May is a failure and we keep it in.** The model trained before 1 May had no post-regime examples; its AUC was below 0.5 and its queue held no fraud. This is why the memo says: retrain every month.

**Ranking by expected rupees (P x amount - (1-P) x 380) did not help**: {MJ['ev_ranked']['frauds_in_queue']} frauds / {inr(MJ['ev_ranked']['net_rs_goodwill_and_contact'])} in May-Jun vs {MJ['final']['frauds_in_queue']} / {inr(MJ['final']['net_rs_goodwill_and_contact'])} for ranking by probability. We kept probability ranking.

## 6. The accuracy trap
| Strategy (May-Jun, {MJ['final']['claims']:,} claims) | Accuracy | Fraud stopped |
|---|---|---|
| Approve everything | {pct(MJ['accuracy_trap_final']['accuracy_predict_nobody'], 2)} | Rs 0 |
| Model queue (top 40 a month called "fraud") | {pct(MJ['accuracy_trap_final']['accuracy_top40_flagged'], 2)} | {inr(MJ['final']['fraud_rupees_caught'])} |

## 7. The money
* Stopped per claim reviewed, June: {inr(jun_f['fraud_rupees_caught'] / 40)} gross; {inr(jun_f['net_rs_goodwill_only'] / 40)} after goodwill; {inr(jun_f['net_rs_goodwill_and_contact'] / 40)} after goodwill and Rs 260 contact cost.
* The Rs 260 "blended cost of a service contact" is ambiguous. We show both readings instead of choosing silently.
* Break-even precision uses the June average caught fraud ({inr(avg_caught)}): {pct(be_goodwill, 0)} (goodwill only), {pct(be_full, 0)} (goodwill + contact).
* Expectation for a test month at {pct(EXP_P, 0)} precision: {exp_frauds:.0f} frauds caught = {inr(exp_caught)} stopped, {exp_fp:.0f} false holds = {inr(exp_fp * 380)} goodwill. Net {inr(exp_net_goodwill)} (goodwill only) or {inr(exp_net_full)} (with Rs 260 per review).
* February-April (before the change, larger claims): net {inr(FEB['final']['net_rs_goodwill_and_contact'])} over 120 reviews.

## 8. Is it the newer partners?
* New outlets (onboarded since 1 Jul 2025): {pt['new_with_any_fraud']} of {pt['new_with_labelled_claims']} with labelled claims have any fraud; {pt['new_partners_listed'] - pt['new_with_labelled_claims']} of the {pt['new_partners_listed']} listed have no labelled claims at all ({pt['new_partners_onboarded_after_train_end']} were onboarded after the data ends). "Clean" for those means "no data", not "verified clean".
* Fraud rate on claims: new outlets {pct(pt['fraud_rate_new'])} vs older outlets {pct(pt['fraud_rate_old'])}. So Ritu's instinct has some support in the rate, and Meenal is right that most new outlets are fine: {pt['new_with_labelled_claims'] - pt['new_with_any_fraud']} of {pt['new_with_labelled_claims']} new outlets with claims have no fraud.
* The five outlets behind most post-May small-claim fraud were all onboarded Nov 2025 - Feb 2026: {', '.join(f"{k} ({v})" for k, v in pt['top5_onboarded'].items())}. Concentration: the top 12 outlets hold {pct(pt['top12_partner_fraud_share'], 0)} of all fraud.
* Onboarding date alone is not a usable rule: it would flag {pt['new_partners_listed']} outlets to reach a handful.

## 9. Smaller checks (read with care: June has {JUN['final']['positives']} frauds, a change of 1-3 frauds is noise)
* **Ablation, June fold:** """ + "; ".join(f"{k}: {v['frauds_in_top40']} of 40 (AUC {v['roc_auc']:.2f})" for k, v in R['ablation_Jun'].items()) + f""".
* **Stale snapshot:** the test file is scored with a snapshot that ages up to 3 months. June fold with a snapshot 0 / 30 / 60 days old: """ + " / ".join(f"{v['frauds_in_top40']} of 40" for v in R['staleness_Jun'].values()) + f""" in the queue. No visible damage in this one fold.
* **Unseen outlets (May-Jun):** {R['unseen_partners_May_Jun']['claims']} claims from {R['unseen_partners_May_Jun']['partners']} outlets with no earlier labelled claims, {R['unseen_partners_May_Jun']['frauds']} frauds. Too few to say anything about cold-start performance.
* **Simple outlet rule (no model):** re-inspect small claims from outlets with 3 or more confirmed frauds at the start of the month. May: {orule['May']['claims_to_inspect']} claims, {orule['May']['frauds_inside']} frauds (the wave had not shown up yet).
  June: {orule['Jun']['claims_to_inspect']} claims from {orule['Jun']['outlets']} outlets, {orule['Jun']['frauds_inside']} frauds ({pct(orule['Jun']['precision'], 0)}), {pct(orule['Jun']['share_of_month_frauds'], 0)} of June's frauds, {inr(orule['Jun']['fraud_rupees_inside'])}.

## 10. What the test predictions look like
* {R['predictions']['rows']:,} claims, {R['predictions']['distinct_scores']:,} distinct scores in [{R['predictions']['min']:.4f}, {R['predictions']['max']:.4f}], mean {R['predictions']['mean']:.3f} (close to the expected fraud rate; scores are probabilities, not rank-compressed).
* Queue threshold {q['threshold']:.3f} flags {', '.join(f'{k}: {v}' for k, v in q['test_flags_per_month'].items())} claims per month (target 40).
* Queue concentration: """ + ", ".join(f"{k} {v}" for k, v in tq.items()) + """ claims. Two of these (SP3118, SP3286) were onboarded in June 2026 and have only two labelled claims, both fraud: strong but thin evidence. SP3300 was onboarded 29 Jul 2026 and has no history, so it is flagged on claim facts alone. Review these by hand before acting on them.

## 11. Known weaknesses
* 141 frauds; June fold has 22. All intervals are wide.
* One regime-consistent fold only (June). May shows the model fails if it is stale.
* Hand-set blend and hyper-parameters (see section 4).
* The test period (Jul-Sep) is scored with a snapshot frozen on 30 Jun, and its true fraud labels will arrive 30+ days late.
* Fraud rate in the test months is unknown; the stated expectation assumes it stays near the post-May level.
"""

# =========================================================================
MEMO = f"""# Memo to Ritu: warranty fraud model

**Decision.** Use the model to choose which 40 claims a month the investigation desk reviews. Do not auto-reject anything. Stop using accuracy as the KPI.

**Why not accuracy.** Approving every claim is {pct(MJ['accuracy_trap_final']['accuracy_predict_nobody'], 1)} accurate and stops no fraud. Even a perfect 40-a-month list would score about the same, and a realistic one scores lower, so accuracy cannot tell a useful model from none. The number to track is **rupees of fraud stopped per claim checked**.

**The number.** In June 2026 the 40 claims the model picked included {jun_f['frauds_in_queue']} real frauds ({pct(jun_f['precision'], 0)}) worth {inr(jun_f['fraud_rupees_caught'])}: **about {inr(jun_f['fraud_rupees_caught'] / 40)} stopped per claim checked**. Picking at random would find about 1 fraud.
For the July-September claims I expect about 10 frauds in each 40 (a plausible range is 3 to 18), roughly {inr(exp_caught)} stopped a month, against about {inr(fraud_per_month)} a month of fraud paid in May-June.

**The rupees, honestly.** Each genuine claim held costs Rs 380 goodwill. To pay for itself, a review must find fraud about {pct(be_goodwill, 0)} of the time ({pct(be_full, 0)} if the Rs 260 contact cost is charged per review). My expectation, {pct(EXP_P, 0)}, is near break-even:
about {inr(exp_net_goodwill)} a month after goodwill, {inr(exp_net_full)} if Rs 260 per review is counted. In May the model, trained before the rule change, found nothing. **It must be retrained every month.**

**New partners.** Your instinct has some support: new outlets show {pct(pt['fraud_rate_new'], 0)} fraud on claims against {pct(pt['fraud_rate_old'], 0)} for older ones. But {pt['new_with_labelled_claims'] - pt['new_with_any_fraud']} of the {pt['new_with_labelled_claims']} new outlets with claims have none, as Meenal says. The problem is a handful of outlets:
{top5_txt}. They hold {pct(pt['post_may_small_top5_share_of_fraud'], 0)} of post-May small-claim fraud.

**Next week.**
1. Have Meenal's team review the outlets that fill the top of the list: {', '.join(tq.keys())}. SP3118 and SP3286 are June-onboarded with two claims each, and SP3300 has no history, so check by hand before suspending anyone.
2. Put small claims (under Rs 2,000) from outlets with 3 or more confirmed frauds back on inspection. In June that rule would have covered {orule['Jun']['claims_to_inspect']} claims from {orule['Jun']['outlets']} outlets and {pct(orule['Jun']['share_of_month_frauds'], 0)} of the month's fraud, with no model (in May it would have caught nothing: the wave had not started).
3. Ask the investigation desk to record every outcome within 30 days; open cases are being stored as 0 and that hides fraud from the model.
4. Re-run the training script on the first working day of each month.

**What it will miss.** First-time fraud from outlets with no history (about {dq['test_rows_unseen_partner']} test claims come from {dq['test_partners_not_in_train']} such outlets). Evidence rests on 141 frauds in total, so treat every figure here as an estimate.
"""

# =========================================================================
DECISIONS = f"""# Decisions and ambiguities

| # | Question | Decision | Why |
|---|---|---|---|
| 1 | Undecided labels | Drop the {dq['undecided_blank_labels']} blank rows from training/evaluation | They are not negatives |
| 2 | Legacy Zoho 0s may be undecided | Keep, cannot identify; state the risk | Dropping all legacy rows loses {dq['legacy_rows_decided']:,} of {dq['decided_claims']:,} claims |
| 3 | Duplicate claim_ids | Keep the last submission; test has none | A bounced claim re-submitted is one claim |
| 4 | UTC vs IST | Nothing to convert | The UTC issue applies to resolution events, absent from these files; `submitted_at` is IST |
| 5 | Rs 260 contact cost | Reported both ways | Policy text is ambiguous (per review vs blended overhead) |
| 6 | Label delay | 30 days for training rows; frozen snapshot for scoring | An outcome is not known on filing day. The first version said 14 in the docs and used 30 in code; docs are now generated |
| 7 | Inspection fields | Excluded | Exist only for inspected claims; inspection of small claims stopped on 1 May |
| 8 | Free text | Never a feature, never sent to an LLM; whitelist check; {dq['injected_or_unrecognised_train_description_rows']} injected rows in train, {dq['injected_or_unrecognised_test_description_rows']} in test | The 12 + 7 stock phrases carry no signal; injection rows ask for a misleading evaluation |
| 9 | Scoring-time partner history | One frozen snapshot (labels up to the last labelled claim) | Same code path for the API, predictions.csv and validation |
| 10 | Class weighting | None | The first version used scale_pos_weight ~80, which squeezed every score into 0.44-0.56 with 41 distinct values |
| 11 | Final model | 0.7 CatBoost (depth 3) + 0.3 logistic regression, probabilities | Rank-averaging and the rules score were tried; this blend was not worse than either part and breaks ties. Hand-set, see EVIDENCE section 4 |
| 12 | KPI | Pushed back: accuracy replaced by rupees stopped per claim checked | Accuracy is {pct(MJ['accuracy_trap_final']['accuracy_predict_nobody'], 1)} for doing nothing |
| 13 | Public vs private repo | Private; `model/reference.json` holds per-outlet fraud counts | Client data must not be published |
| 14 | Reasons text | Deterministic templates filled from the claim and outlet history. No LLM in the product | Must run with no key; nothing to fail |
"""

# =========================================================================
REC = f"""# Recording script (3:00 max, no slides)

**0:00-0:20 Brief and trap.** Share `README.md`. "Board wants accuracy above 97%. Doing nothing scores {pct(MJ['accuracy_trap_final']['accuracy_predict_nobody'], 1)}, so I changed the KPI to rupees stopped per claim checked, because finance can only review 40 a month."

**0:20-0:55 What I found in the data.** Open `EVIDENCE.md` section 2-3. Duplicates ({dq['duplicate_rows_removed']}), {dq['undecided_blank_labels']} blank labels, {dq['injected_or_unrecognised_train_description_rows']} rows of injected instructions in the description column (show one), and the 1 May change: small-claim fraud {pct(rate(rg['pre_small']), 1)} to {pct(rate(rg['post_small']), 1)} when inspection stopped.

**0:55-1:30 What I tried and threw away.** First version: class-weighted CatBoost, scores crammed into 0.44-0.56, API not matching the CSV, wrong outlet list in the memo, and a detector that flagged every "failure" note (1,227 false flags). I threw away inspection fields, free text, serial counts, volume counts, the heavy weighting, and the expected-rupee ranking (it did not help).

**1:30-2:10 Evidence and failures.** `EVIDENCE.md` section 5. June: {jun_f['frauds_in_queue']} of 40 vs random ~1. Then May: 0 of 40. "A model trained before 1 May never saw the new pattern, so it must be retrained monthly." State the intervals and that June has {JUN['final']['positives']} frauds.

**2:10-2:40 The service.** Run the README commands in a clean folder. Open the screen, load the suspicious claim (outlet history + near-Rs 2,000 reasons), then the clean claim, then paste a claim with injected text (warning, same score). Call `/score` once with curl. Run `pytest` (passes without the data folder).

**2:40-3:00 The ask.** `memo_to_ritu.md`: use the model for the 40-a-month list, put five outlets back on inspection, record outcomes within 30 days, retrain monthly. "Break-even is near {pct(be_goodwill, 0)}-{pct(be_full, 0)} precision, so the money is in the outlet action more than the model."
"""

# =========================================================================
FORM = f"""# Submission form: Kestrel Home, Warranty Claim Review (Variant C)

Items in [square brackets] are for the candidate to fill; everything else is generated from the results.

**1. What did you build, and what business outcome does it move? State the number and the money.**
A review-queue ranking (CatBoost + logistic regression on claim facts and each outlet's as-of fraud history) with an API and a screen. It picks the 40 claims a month the investigation desk should review.
In June 2026 its 40 picks held {jun_f['frauds_in_queue']} real frauds worth {inr(jun_f['fraud_rupees_caught'])}, about {inr(jun_f['fraud_rupees_caught'] / 40)} stopped per claim checked ({pct(jun_f['precision'], 0)} precision vs {pct(JUN['random_expected_precision'], 1)} random).
Net of Rs 380 goodwill it is {inr(jun_f['net_rs_goodwill_only'])} for June; with Rs 260 per review also charged, {inr(jun_f['net_rs_goodwill_and_contact'])}. In May a stale model found 0 of 40, so the number is conditional on monthly retraining.

**2. What score do you expect predictions.csv to get on the hidden outcomes, on which metric, and why that metric? How did you estimate it?**
Precision in the top 40 per month: about {pct(EXP_P, 0)} (plausible 8-45%), i.e. about {exp_frauds:.0f} frauds per 40 reviews; ROC-AUC about 0.85 (plausible 0.65-0.95).
Why: the fraud rate is 1-3% and the desk can review 40 a month, so the top of the list is what matters; accuracy would reward approving everything.
How: rolling monthly backtests with a frozen outlet-history snapshot (the way the test file is scored). June (regime-aware, {JUN['final']['positives']} frauds): precision {pct(jun_f['precision'], 1)}, AUC {jun_f['roc_auc']:.2f}, interval {ci(JUN, 'precision_ci', lambda v: pct(v, 0))}.
May (stale model): 0%. Pooled May-Jun: {pct(MJ['final']['precision'], 1)}. I stated 25%, between the pooled and June figures, because the test months are longer, the snapshot ages up to 3 months, and the fraud pattern may drift.

**3. How do you know it works? Sample size, how you checked, error rate, what it gets wrong.**
11,146 decided claims, 141 frauds; monthly rolling-origin validation Feb-Jun 2026 (no random splits, no leakage: outlet history is as-of with a 30-day label delay); partner-clustered bootstrap intervals.
June: {jun_f['frauds_in_queue']} of 40 correct, {jun_f['false_holds']} genuine claims held. May: 0 of 40. It gets wrong: outlets with no history, any month after the fraud pattern changes, and genuine claims at flagged outlets.
Rules baseline in June: {JUN['rules']['frauds_in_queue']} of 40; plain logistic regression {JUN['lr']['frauds_in_queue']}; CatBoost alone {JUN['cb']['frauds_in_queue']}. The final blend ({jun_f['frauds_in_queue']}) is not clearly better than CatBoost alone; the differences are within noise.

**4. Did you change, narrow or push back on the client's ask?**
Yes. (a) Replaced accuracy with rupees stopped per claim checked: "approve everything" is {pct(MJ['accuracy_trap_final']['accuracy_predict_nobody'], 1)} accurate. (b) Tested "it's the newer partners": new outlets show {pct(pt['fraud_rate_new'], 0)} fraud on claims vs {pct(pt['fraud_rate_old'], 0)}, but most new outlets are clean and five outlets hold {pct(pt['post_may_small_top5_share_of_fraud'], 0)} of post-May small-claim fraud. (c) Said the queue is near break-even and recommended outlet-level action and monthly retraining.

**5. What is wrong with what you are handing us, or with the data?**
Data: {dq['duplicate_rows_removed']} duplicate rows; {dq['undecided_blank_labels']} blank labels; legacy Zoho undecided cases stored as 0 (cannot be identified); {dq['injected_or_unrecognised_train_description_rows']} description rows containing instructions to an AI reviewer (train; none in test); messy serials; the policy's UTC note concerns fields not in these files; {dq['test_partners_not_in_train']} test outlets never seen in training.
Mine: only 141 frauds and 22 in the June fold, so intervals are wide; blend weights and hyper-parameters were set by hand on the same folds (mildly optimistic); one regime-consistent fold; the first version of this project (class-weighted model, hand-typed documents) had wrong numbers, wrong outlet IDs, a 41-value score range and an API that did not match the CSV. All repaired; documents are now generated from the results file.
Two June-onboarded outlets (SP3118, SP3286) rank high on two claims each: thin evidence.

**6. What did you deliberately leave out, and why?**
Free text and inspection fields (no signal / regime-dependent), serial repeat counts, claim-volume counts, hour of day (noise with 141 positives), deep models, an LLM in the product (nothing to gain over templates; must run without a key), expected-rupee ranking (tested, no better).

**7. Anything you built or found that nobody asked for?**
The injected instructions in the free text; the May-fold failure showing monthly retraining is required; the outlet-level rule (no model: outlets with 3+ confirmed frauds at month start) that covered {pct(orule['Jun']['share_of_month_frauds'], 0)} of June's fraud but nothing in May; a parity test that the API and predictions.csv agree; documents generated from results.

**8. What did you use AI for?**
[Fill in: tools/models used, where they helped, where they wasted time, what you threw away, and cost. Be specific. Suggested content: AI assistant(s) for building, a second review pass that found the bugs listed in item 5, and nothing inside the product.] Recording: [link]

**9. Public Google Drive link:** [link]

**10. Someone picks this up on Monday and you are unreachable. The three things they need.**
(1) `pip install -r requirements.txt`, then `python -m uvicorn src.app:app`; tests: `python -m pytest tests`. Retrain with the client's `data/` folder: `python -m src.train && python -m src.make_docs`.
(2) Retrain on the first working day of each month with newly decided outcomes; a model older than a month missed all fraud in May.
(3) The list is a ranking for 40 human reviews a month, not an auto-reject; check thinly evidenced outlets by hand before acting.

**11. Honest hours spent:** [number]

**12. GitHub repo link:** [link; keep the repo private unless it contains no data. `model/reference.json` contains per-outlet fraud counts, so share access rather than publishing.]

**13. What does one prediction cost, and what would a month cost (about 750 claims)?**
No paid calls. A prediction is a CatBoost and a logistic regression evaluation on one row, a few milliseconds of CPU: Rs 0 per prediction. 750 x Rs 0 = Rs 0 a month, excluding the cost of running the server. If an LLM were added later for wording, the cost would be tokens per call x price per token x 750; it is not in this product.
"""

# =========================================================================
for name, text in [("EVIDENCE.md", EVIDENCE), ("memo_to_ritu.md", MEMO), ("DECISIONS.md", DECISIONS),
                   ("recording_script.md", REC), ("submission-form.md", FORM)]:
    (ROOT / name).write_text(text)
print("wrote 5 documents")
